global:
  scrape_interval: 1m

scrape_configs:
  - job_name: openweathermap
    static_configs:
      - targets:
        - openweathermap:80

rule_files:
  - /etc/prometheus/rules.d/*.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
